### PR TITLE
DBAAS-149 Upgrade dynamic plugin sdk and remove unnecessary UI and use build dev temporarily

### PR DESCRIPTION
**Pull request by yzhao583**
- Upgrade dynamic plugin sdk
- Remove unnecessary UI
- Use build dev temporarily
- Remove package.lock.json since we have yarn.lock

### CODE REVIEW

**Comment by tchughesiv** [comment]
@yzhao583 lgtm... should we add package-lock.json to `.gitignore` ?

**Comment by yzhao583** [comment]
> @yzhao583 lgtm... should we add package-lock.json to `.gitignore` ?

@tchughesiv We use yarn in this project, so we should not have `package.lock.json`, we should have `yarn.lock`, and I personally think we should check the `yarn.lock` in since we want the dependencies installed are the same every time.

**Comment by tchughesiv** [comment]
> > @yzhao583 lgtm... should we add package-lock.json to `.gitignore` ?
> 
> @tchughesiv We use yarn in this project, so we should not have `package.lock.json`, we should have `yarn.lock`, and I personally think we should check the `yarn.lock` in since we want the dependencies installed are the same every time.

agree @yzhao583  ... was just thinking if we add `package-lock.json` to `.gitignore` it won't be accidentally committed by someone in the future.

**Review by redhatHameed — DISMISSED** [review]
Lgtm and verified on cluster connection are now showing. 

Screen Shot 2021-09-09 at 5 46 23 PM
Screen Shot 2021-09-09 at 5 46 09 PM

**Comment by yzhao583** [comment]
> > > @yzhao583 lgtm... should we add package-lock.json to `.gitignore` ?
> > 
> > 
> > @tchughesiv We use yarn in this project, so we should not have `package.lock.json`, we should have `yarn.lock`, and I personally think we should check the `yarn.lock` in since we want the dependencies installed are the same every time.
> 
> agree @yzhao583 ... was just thinking if we add `package-lock.json` to `.gitignore` it won't be accidentally committed by someone in the future.

@tchughesiv Added :)

**Review by redhatHameed — APPROVED** [review]

**Comment by jeremyary** [comment]
> @tchughesiv Added :)

Sounds good. Should we remove `package-lock.json` from this commit since we're adding it to `.gitignore`? It's going to get committed and then ignored going forward as it stands right now.

**Review by jeremyary — APPROVED** [review]

**Pull request merged**
