### PR TITLE
DBAAS 366 Show empty state when there is no provider account

### PR DESCRIPTION
**Pull request by yzhao583**
Jira: [https://issues.redhat.com/browse/DBAAS-366](https://issues.redhat.com/browse/DBAAS-366)

image

### CODE REVIEW

**Review by olavtar — DISMISSED** [review]
LGTM, my only question, do we want to show them any UI when there is an error in fetchInstancesFailed?

**Comment by yzhao583** [comment]
> LGTM, my only question, do we want to show them any UI when there is an error in fetchInstancesFailed?

There is already UI for that

**Comment by yzhao583** [comment]
> > LGTM, my only question, do we want to show them any UI when there is an error in fetchInstancesFailed?
> 
> There is already UI for that
> 
> @yzhao583 I meant if we are ok to show the Provider Account field even when there is an error?

Yes, I think we need that to allow users to switch provider account

**Comment by jeremyary** [comment]
@yzhao583 PTAL at merge conflict following merging Tommy's PR? thanks!

**Review by jeremyary — APPROVED** [review]

**Pull request merged**
