### PR TITLE
[DBAAS-889] v1beta1 api changes

### PR DESCRIPTION
**Pull request by tchughesiv**
depends on https://github.com/RHEcosystemAppEng/dbaas-operator/pull/296

Signed-off-by: Tommy Hughes <tohughes@redhat.com>

### CODE REVIEW

**Comment by jeremyary** [comment]
looks ok to me for what that's worth, but will wait for someone with more knowledge to weigh in :)

**Review by olavtar — APPROVED** [review]
LGTM

**Comment by tchughesiv** [comment]
don't merge this until the required operator PR is also merged

**Review by yzhao583 — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
