### PR TITLE
DBAAS-372 Disabling "Create Database Instance" button

### PR DESCRIPTION
**Pull request by olavtar**
Disabling "Create Database Instance" button when there are no database resource available.

Signed-off-by: Olga Lavtar <olavtar@redhat.com>

### CODE REVIEW

**Review by yzhao583 — COMMENTED** [review]
@olavtar Can you run `yarn run-dev` and commit again? Thanks

**Review by yzhao583 — APPROVED** [review]
LGTM

**Review by jeremyary — APPROVED** [review]

**Comment by jeremyary** [comment]
Does this only fix our button off the dev workflow? If so, is it possible to also do this for the button above admin area (it just becomes the one option of creating a PA instead of multi-button)?

**Comment by olavtar** [comment]
> Does this only fix our button off the dev workflow? If so, is it possible to also do this for the button above admin area (it just becomes the one option of creating a PA instead of multi-button)?

Yes, only the dev workflow. In the Admin view we don't choose a provider nor a provider account. Are you talking about the empty state then?

**Review by tchughesiv — APPROVED** [review]
lgtm

**Comment by jeremyary** [comment]
just to close the loop on my last question, our new empty state when no PA and state when there's a PA but no instance already handle the use case I had in mind correctly. g2g.

**Pull request merged**
