### PR TITLE
New design for the Dev table

### PR DESCRIPTION
**Pull request by olavtar**
Finished implementation of the new design for the Dev table
Signed-off-by: Olga Lavtar <olavtar@redhat.com>

### CODE REVIEW

**Review by yzhao583 — CHANGES_REQUESTED** [review]
@olavtar Thanks for the work. In general it looks good, but here are 2 comments.

- The instanceTable component is not only used by the instanceListPage component, but also the instanceForm component, so please take a look what is affected in the instanceForm component.
- Please remove the show/hide table related logic, variables, function if there are not needed anymore. Thanks

**Review by tchughesiv — CHANGES_REQUESTED** [review]
run a `yarn format` and commit changes

**Review by yzhao583 — CHANGES_REQUESTED** [review]
@olavtar Can we remove the show/hide the `connectionStatusTable` related variables and functions? For example [https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/52/files#diff-8f1b661c33c09122c2756362acc9f2531de36cec7036f211c25c175e8766bbebL44](https://github.com/RHEcosystemAppEng/dbaas-dynamic-plugin/pull/52/files#diff-8f1b661c33c09122c2756362acc9f2531de36cec7036f211c25c175e8766bbebL44)

**Review by yzhao583 — APPROVED** [review]
LGTM

**Pull request merged**
