### PR TITLE
Developer view (UI) support for CockroachDB Cloud operator - DBaaSCon

### PR DESCRIPTION
**Pull request by myeung18**
Developer view (UI) support for CockroachDB Cloud operator - DBaaSConnection

### CODE REVIEW

**Review by yzhao583 — COMMENTED** [review]
@myeung18 The code looks good to me thanks! Have you tested the change locally? I mean front-end fetch icon etc, from CRD, does it work properly?

**Comment by myeung18** [comment]
> @myeung18 The code looks good to me thanks! Have you tested the change locally? I mean front-end fetch icon etc, from CRD, does it work properly?

Yes, things work fine so far.

**Comment by yzhao583** [comment]
@jeremyary @myeung18 Is there anything else we need to do for this PR? Do we want to merge it?

**Comment by tchughesiv** [comment]
@yzhao583 should we wait for https://github.com/RHEcosystemAppEng/dbaas-operator/pull/97 to merge? or does it matter?

**Comment by yzhao583** [comment]
@tchughesiv Oh I see, yes we need to wait for it, thanks :)

**Comment by myeung18** [comment]
@yzhao583  what are those failed checked? 
any advice how to fix them?

**Comment by yzhao583** [comment]
@myeung18 If someone approve it should be fine

**Review by tchughesiv — CHANGES_REQUESTED** [review]
please run a `yarn format` and commit changes

**Review by tchughesiv — APPROVED** [review]
lgtm

**Pull request merged**
